spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev  #开发环境
  application:
    name: springcloud-config-atguigu-dev
    
---
spring:
  profiles: test   #测试环境
  application:
    name: springcloud-config-atguigu-test8
    
---
spring:
  profiles: prod   #生产环境
  application:
    name: springcloud-config-atguigu-prod9

#请保存为utf-8111aaqqe1332131'''21121sfcddaf3214
