server:
  port: 3355


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root


eureka:
  client:
    #表示是否将自己注册进EurekaServer  默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true
    #这样才能配合Ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #因为我们在做注册中心集群，需要同时注册到两个eureka上面，如果是单个eureka，就不用写两个，即：
      #defaultZone: http://eureka7001.com:7001/eureka即可
